stages:
  downland:
    cmd: source downlanding.txt
    deps:
    - downlanding.txt
    outs:
    - news.csv
    - navec_hudlit_v1_12B_500K_300d_100q.tar
  prepare_data:
    cmd: python3 prepare_data.py
    deps:
    - prepare_data.py
    outs:
    - data/train
    - data/test